sudo: false
language: csharp
solution: CSF.Screenplay.sln

addons:
  sauce_connect:
    direct_domains: google.com
  apt:
    packages:
      - mono-xsp4

matrix:
  include:
    - env:
      - SAUCE_USERNAME="craigfowler_screenplay"
      - secure: "ZI+FDrm6aec9HNMS4bbkgUzpeqVwy11flgnqWpYIyG12GzKQmrdXqMoAwD1kimIRNvry4r/z33GhBPDQaHly8edFzlkG4H8ITCyE48qttrVG71j5yYsyk6RLPm28zhcuhmnlalssk9jCsp09YFJ3zRO3Ayj/vboxTkQFhTa8d6nwag+MpfiVZVRdouO3qcKL3lPeWaQECo9hpX8o5MrQDCWprqg7b0ZMgW0vi5bqIFAmKoE/hn+qgp7BUQeVc983D8KClqYBsoJ09crn5ifd3CeCoOzeyczyS/DPrRgOOT63VdllGEQGKQZ78RY1LoloqEbbRI5ibjq7vuc8Er73yzxSbBbnKhG6nHRdfdNwxn2IAtZw86tpNSaKO1u8lprFDLbdCbHu42J6qQx4R8HZcq12Myv1eRYvupQrFv3mDAHK+NWYwCMKvouof50RNnJiFn6zcisvNQXCgG8NWeDBWbszRIwgvmQLsNB/vHCzrHO1bAT4lEYNuFVoUstO8t1r0C7ZVM6Qruuj46J0ZESTo10hUoHCohutdJ0ZAmH4ZxmW57L+BO1eFarkM7hmEZX6fImn0fobNHhSaEy+dNpYa9OS6n4iE6N4teTw20rpZ/AjkLUvJXjMh/YPkQ7M4VvDLqUHh5MPqAbgq3tUEfgPTm+lNy9QibquFwBRsAb3HRU="
      - BROWSER_PLATFORM="Windows 10"
      - BROWSER_NAME="Chrome"
    - env:
      - SAUCE_USERNAME="craigfowler_screenplay"
      - secure: "ZI+FDrm6aec9HNMS4bbkgUzpeqVwy11flgnqWpYIyG12GzKQmrdXqMoAwD1kimIRNvry4r/z33GhBPDQaHly8edFzlkG4H8ITCyE48qttrVG71j5yYsyk6RLPm28zhcuhmnlalssk9jCsp09YFJ3zRO3Ayj/vboxTkQFhTa8d6nwag+MpfiVZVRdouO3qcKL3lPeWaQECo9hpX8o5MrQDCWprqg7b0ZMgW0vi5bqIFAmKoE/hn+qgp7BUQeVc983D8KClqYBsoJ09crn5ifd3CeCoOzeyczyS/DPrRgOOT63VdllGEQGKQZ78RY1LoloqEbbRI5ibjq7vuc8Er73yzxSbBbnKhG6nHRdfdNwxn2IAtZw86tpNSaKO1u8lprFDLbdCbHu42J6qQx4R8HZcq12Myv1eRYvupQrFv3mDAHK+NWYwCMKvouof50RNnJiFn6zcisvNQXCgG8NWeDBWbszRIwgvmQLsNB/vHCzrHO1bAT4lEYNuFVoUstO8t1r0C7ZVM6Qruuj46J0ZESTo10hUoHCohutdJ0ZAmH4ZxmW57L+BO1eFarkM7hmEZX6fImn0fobNHhSaEy+dNpYa9OS6n4iE6N4teTw20rpZ/AjkLUvJXjMh/YPkQ7M4VvDLqUHh5MPqAbgq3tUEfgPTm+lNy9QibquFwBRsAb3HRU="
      - BROWSER_PLATFORM="Windows 10"
      - BROWSER_NAME="Firefox"
    - env:
      - SAUCE_USERNAME="craigfowler_screenplay"
      - secure: "ZI+FDrm6aec9HNMS4bbkgUzpeqVwy11flgnqWpYIyG12GzKQmrdXqMoAwD1kimIRNvry4r/z33GhBPDQaHly8edFzlkG4H8ITCyE48qttrVG71j5yYsyk6RLPm28zhcuhmnlalssk9jCsp09YFJ3zRO3Ayj/vboxTkQFhTa8d6nwag+MpfiVZVRdouO3qcKL3lPeWaQECo9hpX8o5MrQDCWprqg7b0ZMgW0vi5bqIFAmKoE/hn+qgp7BUQeVc983D8KClqYBsoJ09crn5ifd3CeCoOzeyczyS/DPrRgOOT63VdllGEQGKQZ78RY1LoloqEbbRI5ibjq7vuc8Er73yzxSbBbnKhG6nHRdfdNwxn2IAtZw86tpNSaKO1u8lprFDLbdCbHu42J6qQx4R8HZcq12Myv1eRYvupQrFv3mDAHK+NWYwCMKvouof50RNnJiFn6zcisvNQXCgG8NWeDBWbszRIwgvmQLsNB/vHCzrHO1bAT4lEYNuFVoUstO8t1r0C7ZVM6Qruuj46J0ZESTo10hUoHCohutdJ0ZAmH4ZxmW57L+BO1eFarkM7hmEZX6fImn0fobNHhSaEy+dNpYa9OS6n4iE6N4teTw20rpZ/AjkLUvJXjMh/YPkQ7M4VvDLqUHh5MPqAbgq3tUEfgPTm+lNy9QibquFwBRsAb3HRU="
      - BROWSER_PLATFORM="Windows 10"
      - BROWSER_NAME="Internet Explorer"
    - env:
      - SAUCE_USERNAME="craigfowler_screenplay"
      - secure: "ZI+FDrm6aec9HNMS4bbkgUzpeqVwy11flgnqWpYIyG12GzKQmrdXqMoAwD1kimIRNvry4r/z33GhBPDQaHly8edFzlkG4H8ITCyE48qttrVG71j5yYsyk6RLPm28zhcuhmnlalssk9jCsp09YFJ3zRO3Ayj/vboxTkQFhTa8d6nwag+MpfiVZVRdouO3qcKL3lPeWaQECo9hpX8o5MrQDCWprqg7b0ZMgW0vi5bqIFAmKoE/hn+qgp7BUQeVc983D8KClqYBsoJ09crn5ifd3CeCoOzeyczyS/DPrRgOOT63VdllGEQGKQZ78RY1LoloqEbbRI5ibjq7vuc8Er73yzxSbBbnKhG6nHRdfdNwxn2IAtZw86tpNSaKO1u8lprFDLbdCbHu42J6qQx4R8HZcq12Myv1eRYvupQrFv3mDAHK+NWYwCMKvouof50RNnJiFn6zcisvNQXCgG8NWeDBWbszRIwgvmQLsNB/vHCzrHO1bAT4lEYNuFVoUstO8t1r0C7ZVM6Qruuj46J0ZESTo10hUoHCohutdJ0ZAmH4ZxmW57L+BO1eFarkM7hmEZX6fImn0fobNHhSaEy+dNpYa9OS6n4iE6N4teTw20rpZ/AjkLUvJXjMh/YPkQ7M4VvDLqUHh5MPqAbgq3tUEfgPTm+lNy9QibquFwBRsAb3HRU="
      - BROWSER_PLATFORM="Windows 10"
      - BROWSER_NAME="MicrosoftEdge"
    - env:
      - SAUCE_USERNAME="craigfowler_screenplay"
      - secure: "ZI+FDrm6aec9HNMS4bbkgUzpeqVwy11flgnqWpYIyG12GzKQmrdXqMoAwD1kimIRNvry4r/z33GhBPDQaHly8edFzlkG4H8ITCyE48qttrVG71j5yYsyk6RLPm28zhcuhmnlalssk9jCsp09YFJ3zRO3Ayj/vboxTkQFhTa8d6nwag+MpfiVZVRdouO3qcKL3lPeWaQECo9hpX8o5MrQDCWprqg7b0ZMgW0vi5bqIFAmKoE/hn+qgp7BUQeVc983D8KClqYBsoJ09crn5ifd3CeCoOzeyczyS/DPrRgOOT63VdllGEQGKQZ78RY1LoloqEbbRI5ibjq7vuc8Er73yzxSbBbnKhG6nHRdfdNwxn2IAtZw86tpNSaKO1u8lprFDLbdCbHu42J6qQx4R8HZcq12Myv1eRYvupQrFv3mDAHK+NWYwCMKvouof50RNnJiFn6zcisvNQXCgG8NWeDBWbszRIwgvmQLsNB/vHCzrHO1bAT4lEYNuFVoUstO8t1r0C7ZVM6Qruuj46J0ZESTo10hUoHCohutdJ0ZAmH4ZxmW57L+BO1eFarkM7hmEZX6fImn0fobNHhSaEy+dNpYa9OS6n4iE6N4teTw20rpZ/AjkLUvJXjMh/YPkQ7M4VvDLqUHh5MPqAbgq3tUEfgPTm+lNy9QibquFwBRsAb3HRU="
      - BROWSER_PLATFORM="macOS 10.12"
      - BROWSER_NAME="Safari"
      - BROWSER_VERSION="10.1"

install: Tools/Travis.install.sh

script: Tools/Travis.build.sh